server:
  port: 12000

spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.66.66:8848
  zipkin:
    base-url: http://192.168.66.66:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
logging:
  level:
    com:
      yang: debug
    org:
      springframework:
        cloud:
          openfeign: debug
          sleuth: debug

management:
  endpoints:
    web:
      exposure:
        include: *

feign:
  sentinel:
    enabled: true

