server:
  port: 40000


spring:
  application:
    name: gulimall-cart

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.66.66:8848
  redis:
    port: 6379
    host: 192.168.66.66
  session:
    store-type: redis
  zipkin:
    base-url: http://192.168.66.66:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

#配置线程池
gulimall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true

#开启debug日志
logging:
  level:
    org:
      springframework:
        cloud:
          openfeign: debug
          sleuth: debug

