server:
  port: 40000


spring:
  application:
    name: gulimall-cart

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.66.66:8848
  redis:
    port: 6379
    host: 192.168.66.66
  session:
    store-type: redis

#配置线程池
gulimall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'


